- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew-cask
    - homebrew
  vars:
    # Taps
    #
    # e.g.
    # - homebrew/binary
    homebrew_taps:
      - caskroom/cask
      - homebrew/binary
      - homebrew/boneyard
      - homebrew/completions
      - homebrew/science
      - homebrew/versions
      - peco/peco
      - sona-tar/tools

    # Homebrew packages
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - { name: python }
      - { name: ansible }
      - { name: ack }
      - { name: ant }
      - { name: autoconf }
      - { name: autojump }
      - { name: automake }
      - { name: automake112 }
      - { name: awscli }
      - { name: bash-completion }
      - { name: bash-git-prompt }
      - { name: boot2docker }
      - { name: cabal-install }
      - { name: cmake }
    #      - { name: connect }
      - { name: convmv }
      - { name: coreutils }
      - { name: ctags }
      - { name: darcs }
      - { name: docker }
      - { name: docker-completion }
      - { name: docker-machine }
      - { name: docker-swarm }
      - { name: elixir }
      - { name: emacs }
      - { name: erlang }
      - { name: findutils }
      - { name: gcc }
      - { name: gcutil }
      - { name: gdbm }
      - { name: gettext }
      - { name: gflags }
      - { name: ghc }
      - { name: ghq }
      - { name: ghs }
      - { name: git }
      - { name: git-crypt }
      - { name: giter8 }
      - { name: gnu-sed }
      - { name: gnutls }
      - { name: go }
      - { name: gradle }
      - { name: graphviz }
      - { name: hub }
      - { name: leiningen }
      - { name: lnav }
      - { name: lua }
      - { name: markdown }
      - { name: maven }
      - { name: mercurial }
      - { name: mobile-shell }
      - { name: mysql }
      - { name: nkf }
      - { name: node }
      - { name: nvm }
      - { name: openssl }
      - { name: packer }
      - { name: packer-completion }
      - { name: peco }
      - { name: pkg-config }
      - { name: pstree }
      - { name: pyenv }
      - { name: pyenv-virtualenv }
      - { name: python3 }
      - { name: rbenv }
      - { name: readline }
      - { name: reattach-to-user-namespace }
      - { name: rebar }
      - { name: ruby-build }
      - { name: s3cmd }
      - { name: scala }
      - { name: sbt }
      - { name: shellcheck }
      - { name: source-highlight }
      - { name: subversion }
      - { name: subversion17, install-option: with-unicode-path }
      - { name: tig }
      - { name: tmux }
      - { name: tree }
      - { name: typesafe-activator }
      - { name: vagrant-completion }
      - { name: vim }
      - { name: weechat }
      - { name: wget }

    # Taps for Casks
    homebrew_cask_taps:
      - caskroom/versions
      - caskroom/fonts

    # Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - { name: alfred } # no need this since alfred v 2.6
      - { name: 1password }
      - { name: appcleaner }
      - { name: atom }
      - { name: bartender }
      - { name: dash }
      - { name: dropbox }
      - { name: evernote }
      - { name: firefox }
      - { name: flux }
      - { name: font-ricty-diminished }
      - { name: geektool }
      - { name: gitter }
      - { name: google-chrome }
      - { name: intellij-idea-ce }
      - { name: istat-menus }
      - { name: iterm2 }
      - { name: java }
      - { name: kindle }
      - { name: macwinzipper }
      - { name: send-to-kindle }
      - { name: shiftit }
      - { name: skitch }
      - { name: skype }
      - { name: sourcetree }
      - { name: spotify }
      - { name: teleport }
      - { name: todoist }
      - { name: vagrant }
      - { name: virtualbox }

