# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme


shell = "zsh"
apply = ["defer"]
[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"


[plugins]
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.debug]
inline = '''
if [ -f "$HOME/.zshrc.debug" ]; then
    alias log='>&2 echo \[$(basename ${(%):-%N})\] '
else;
    alias log=': '
fi
'''

[plugins.zsh]
inline = '''
typeset -U path cdpath fpath manpath
bindkey -e
autoload colors
autoload -Uz compinit
compinit -u
# 補完関数の表示を強化する
zstyle ':completion:*' verbose yes
zstyle ':completion:*' completer _expand _complete _match _prefix _approximate _list _history
zstyle ':completion:*:messages' format '%F{YELLOW}%d'$DEFAULT
zstyle ':completion:*:warnings' format '%F{RED}No matches for:''%F{YELLOW} %d'$DEFAULT
zstyle ':completion:*:descriptions' format '%F{YELLOW}completing %B%d%b'$DEFAULT
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:descriptions' format '%F{yellow}Completing %B%d%b%f'$DEFAULT
# マッチ種別を別々に表示
zstyle ':completion:*' group-name ''
'''

[plugins.zsh-pager]
inline = '''
export LESSCHARSET=utf-8
export LESS="-R"
export EDITOR='vim'
export MANPAGER='less -R'
# colorize man
man() {
    env \
        LESS_TERMCAP_mb=$(printf "\e[1;33m") \
        LESS_TERMCAP_md=$(printf "\e[1;36m") \
        LESS_TERMCAP_me=$(printf "\e[0m") \
        LESS_TERMCAP_se=$(printf "\e[0m") \
        LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
        LESS_TERMCAP_ue=$(printf "\e[0m") \
        LESS_TERMCAP_us=$(printf "\e[1;32m") \
        man "$@"
}
'''

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.asdf]
github = "asdf-vm/asdf"

[plugins.dotfiles-defer]
local = "~/.zshrc.d"

[plugins.local-dotfiles-defer]
local = "~/.local/.zshrc.d"

[plugins.dotfiles-sync]
local = "~/.zshrc.d/sync"

[plugins.local-dotfiles-sync]
local = "~/.local/.zshrc.d/sync"

[plugins.home-bin]
local = "~/bin"
apply = ["PATH"]

[plugins.local-bin]
local = "~/.local/bin"
apply = ["PATH"]

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.ssh-agent-multiplexer]
inline = '''
launchctl load ~/Library/LaunchAgents/ssh-agent-multiplexer.plist >/dev/null 2>&1 || true
launchctl start com.github.everpeace.ssh-agent-multiplexer
export SSH_AUTH_SOCK=/Users/everpeace/.ssh/ssh-agent-multiplexer/agent.sock
'''
