---
- name: Open Taps
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_taps
  when: homebrew_taps

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install/Upgrade Homebrew packages
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: homebrew_packages
  when: homebrew_packages

- name: brew パッケージの情報保存先ディレクトリを作成
  file: path=brew_info state=directory

- name: brew パッケージの情報を保存
  shell: brew info {{ item }} > brew_info/{{ item }}
  with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
